---
# tasks file for libvirt-provision

################################################################################
### Set dynamic variables
################################################################################

# Generate MAC addresses using SHA1 on VM name
# Output:
# {
#   "ubuntu-test": {
#     "mac": "42:4d:01"
# }
#
- name: Define VMs list
  set_fact:
    __libvirt_vms: "{{ libvirt_vms }}"

- name: Calculate MAC addresses for VMs
  set_fact:
    __libvirt_vm_mac: >
      { "{{ item.key }}": { "mac": "{{ libvirt_mac_prefix }}:{% for mac_part in (item.key | hash('sha1'))[-6:] | slice(3) %}{{ mac_part | join('') }}{{ '' if loop.last else ':' }}{% endfor %}" } }
  with_dict: "{{ libvirt_vms }}"
  register: __libvirt_vm_macs

- name: Associate MAC address with VMs
  set_fact:
    __libvirt_vms: "{{ __libvirt_vms | combine(item, recursive=True) }}"
  with_items: "{{ __libvirt_vm_macs.results | map(attribute='ansible_facts.__libvirt_vm_mac') | list }}"

- name: Show the list of VMs
  debug:
    msg: "{{ __libvirt_vms }}"
    verbosity: 2

################################################################################
### Install dependencies
################################################################################

- name: Install python-pip
  package:
    state: present
    name: python-pip

- name: Install nsupdate python pip dependency
  pip:
    state: present
    name: dnspython

################################################################################
### Manage VMs
################################################################################

- import_tasks: create.yml
  when: libvirt_vm_state == 'create'

- import_tasks: delete.yml
  when: libvirt_vm_state == 'delete'

################################################################################
### Manage DNS entries
################################################################################

- import_tasks: dns.yml